kind: ConfigMap
apiVersion: v1
metadata:
  name: app-config-rhdh
data:
  app-config-rhdh.yaml: |
    app:
      title: Red Hat Developer Hub
      baseUrl: https://backstage-developer-hub-rhdh-ado.${basedomain}
    backend:
      auth:
        keys:
          - secret: ${BACKEND_SECRET}
      baseUrl: https://backstage-developer-hub-rhdh-ado.${basedomain}
      cors:
        origin: https://backstage-developer-hub-rhdh-ado.${basedomain} 
    auth:
      environment: production
      providers:
        microsoft:
          production:
            clientId: ${AUTH_AZURE_CLIENT_ID}
            clientSecret: ${AUTH_AZURE_CLIENT_SECRET}
            tenantId: ${AUTH_AZURE_TENANT_ID}
    signInPage: microsoft     
  
    integrations:
      azure:
       - host: dev.azure.com
         credentials:
          - organizations:
              - ${organization}
            personalAccessToken: ${ADO_PAT}

      
    catalog:
      rules:
        - allow: [Component, System, Group, Resource, Location, Template, API, User, Domain, Type]    
      locations:
        - type: url
          target: https://dev.azure.com/ramyessawy/_git/rhdh_ado/rhdp_repo/?path=/catalog-info.yaml&version=GBmain&_a=contents
          rules:
            - allow: [Component, System, Group, Resource, Location, Template, API, User, Domain, Type]              
      providers:
        azureDevOps:
          yourProviderId: # identifies your dataset / provider independent of config changes
            organization: ${organization}
            project: '*'
            repository: '*' # this will match all repos starting with service-*
            path: /catalog-info.yaml          
        microsoftGraphOrg:
          default:
            clientId: ${AUTH_AZURE_CLIENT_ID}
            clientSecret: ${AUTH_AZURE_CLIENT_SECRET}
            tenantId: ${AUTH_AZURE_TENANT_ID}
            user:
              filter: accountEnabled eq true and userType eq 'member'
            group:
              filter: >
                securityEnabled eq false
                and mailEnabled eq true
                and groupTypes/any(c:c+eq+'Unified')
            schedule:
              frequency: PT1H
              timeout: PT50M

    enabled:
        azure: true
        azureDevOps: true
        microsoftGraphOrg: true  
    permission:
      enabled: true 
      rbac:
        admin:
          superUsers:
            - name: user:default/e3fbf2d8-4337-4b9a-9001-596564482a48                                                     
        